# Generated by Django 5.2 on 2025-04-12 14:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Terms',
            fields=[
                ('term_id', models.AutoField(db_column='term_id', primary_key=True, serialize=False)),
                ('term', models.CharField(db_column='term', max_length=200)),
                ('definition', models.TextField(db_column='definition')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
            ],
            options={
                'db_table': 'terms',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TermAuthors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(db_column='author', max_length=200)),
                ('email', models.EmailField(db_column='email', max_length=254)),
                ('term_id', models.ForeignKey(db_column='term_id', on_delete=django.db.models.deletion.CASCADE, to='network_anki.terms')),
            ],
            options={
                'db_table': 'term_authors',
            },
        ),
    ]
